spring.application.name=${SPRING_APPLICATION_NAME}

# Conexión limpia usando las variables del entorno
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${DB_PASSWORD}
    
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.entity-scan.base-packages=com.example.hydra_Crud.app.Entity
spring.data.jpa.repositories.base-packages=com.example.hydra_Crud.app.Repository